### ISSUE TITLE
Implement client abstraction to update a device.

### ISSUE THREAD

**Issue by jperras** [fictivekin/fl33t-client#2]
Docs: https://www.fl33t.com/docs/rest#update-device

**Comment by jnhmcknight** [comment]
@jperras, is this the functionality that you were looking for? ref: [`Device.update()`](https://fl33t.readthedocs.io/en/latest/models.html#fl33t.models.Device.update)

Read-only device properties will be ignored during the update, leaving only `fleet_id` and `name` as changeable.

```python

device = fl33t_client.get_device(device_id)

# If I want to change the fleet ID of the device and I already know the new fleet ID
device.fleet_id = new_fleet_id
print(device.update())

```

Now that I've told you how it's supposed to work, let me add that the [not-so] smart nature of the model properties was actually causing the above not to work. I've got a fix for it but just need to do some testing on it.

**Comment by jnhmcknight** [comment]
v0.3.5 has been created with an updated `models/base.py` to make the model properties _actual_ properties.

The above example works for me, so it should be good to go for you too. Let me know if there are still problems.

**Comment by jperras** [comment]
I'll pull in v0.3.5 and check it out. Thanks @jnhmcknight!

**Comment by jnhmcknight** [comment]
Did the updated version work for you, @jperras?

**Comment by jperras** [comment]
It did!

**Comment by jnhmcknight** [comment]
Excellent. Closing.
