### ISSUE TITLE
Logger is a bit aggressive on 4xx level responses from API.

### ISSUE THREAD

**Issue by jperras** [fictivekin/fl33t-client#3]
I have a few situations where I perform the equivalent of a create-or-get operation, e.g.

```python
try:
    device = fleet.create_device(device_id='foobar', name='My Great Device', fleet_id='xxx')
except DuplicateDeviceIdError:
    device = fleet.service.get_device(device_id='foobar')
```

which works as expected. However, even though I capture and handle the `DuplicateDeviceIdError`, an exception log is emitted:

```python
409 Client Error: Conflict for url: https://api.fl33t.com/team/<teamid>/device
Traceback (most recent call last):
  File "[…redacted…]/lib/python3.6/site-packages/fl33t/client.py", line 275, in _request
    result.raise_for_status()
  File "[…redacted…]/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.fl33t.com/team/<teamid>/device
```

This was confusing, since the operation succeeded (from my point of view), but there was still an exception log generated.

The pertinent section in the code is: https://github.com/fictivekin/fl33t-client/blob/2cc44267bb7e3919fd71f46ebc8772c4d439be74/fl33t/client.py#L273-L287

Where if an `HTTPError` is raised from `requests`, it is unconditionally logged. This affects the device creation logic: https://github.com/fictivekin/fl33t-client/blob/2cc44267bb7e3919fd71f46ebc8772c4d439be74/fl33t/models/device.py#L134-L136

in that the log is emitted, *and* the `DuplicateDeviceIdError` exception is raised.

I propose that exceptions are logged *only* if they are not explicitly re-raised as a different, client-specific exception.

**Comment by jnhmcknight** [comment]
That makes more sense than the way it works now. We should definitely adjust how the underlying `HTTPError` exceptions are handled.
